/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  //tutorialSidebar2: [{type: 'autogenerated', dirName: '/docs/Caas'}],
  // But you can create a sidebar manually

  overviewSidebar: [
    {
      type: "category",
      label: "Overview",
      items: [
        "overview/introduction",
        "overview/security",
        "overview/environments",
        "overview/api-key",
        "overview/api-changelog",
      ],
    },
  ],
  paasSidebar: [
    {
      type: "category",
      label: "PaaS",
      items: ["paas/teste"],
    },
  ],
  caasSidebar: [
    {
      type: "category",
      label: "CaaS",
      items: ["caas/teste"],
    },
  ],
  gatewaySidebar: [
    {
      type: "category",
      label: "API Overview",
      items: [
        "gateway/api_overview/introduction",
        "gateway/api_overview/authentication",
        "gateway/api_overview/protocol",
        "gateway/api_overview/serialization",
        "gateway/api_overview/rate_limiting",
        "gateway/api_overview/errors",
        "gateway/api_overview/changelog",
      ],
    },
    {
      type: "category",
      label: "Transactions",
      items: [
        "gateway/transactions/generate_new_qr_code",
        "gateway/transactions/search_by_uuid",
        "gateway/transactions/generate_new_qr_code_for_single_or_multiple_orders",
      ],
    },
  ],
};

module.exports = sidebars;
